[package]
name = "saber"
version = "0.1.0"
authors = ["Aaron <aaronzhouqian@ucla.edu>"]
edition = "2018"

[dependencies]
bio_file_reader = {path = "bio_file_reader"}
clap = "2.32.0"
num-traits = "0.2.6"
