[package]
name = "math"
version = "0.1.0"
authors = ["Aaron <aaronzhouqian@ucla.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
rand = "0.6.5"
