[package]
name = "bio_file_reader"
version = "0.1.0"
authors = ["Aaron <aaronzhouqian@ucla.edu>"]
edition = "2018"

[dependencies]
ndarray = {version = "0.12.1"}
rayon = "1.1.0"
math = {path = "../math"}
num = "0.2"

[dev-dependencies]
tempfile = "3.0.8"
ndarray-rand = "0.9.0"
rand = "0.6.5"
